### ISSUE TITLE
Duplicate Trace ID

### ISSUE THREAD

**Issue by jam0cam** [open-telemetry/opentelemetry-java#1531]
**Describe the bug**
In traces where the same name is used, I sometimes get the same trace id. This happens over different app launches. See the screenshots, some duplication is almost an hour apart.  

**Steps to reproduce**
Normal usage should produce this. I have about 15-20 unique traces throughout my app, and I would see duplicates among some of those traces.

**What version and what artifacts are you using?**
`io.opentelemetry:opentelemetry-sdk:0.7.0`
`io.opentelemetry:opentelemetry-exporters-zipkin:0.6.0`

**Environment**
Android emulator, API 28

**Additional context**
on a basic level, this how the trace is done: 
```
val span = tracer.spanBuilder(name.value).startSpan()
...
span.end()
```

**Screenshots from honeycomb**
![image](https://user-images.githubusercontent.com/869467/89918858-8f291d80-dbc8-11ea-92a1-9d65ab29bd95.png)

**Comment by Oberon00** [comment]
I don't think this has anything to do with the name. Probably the seed or algorithm of the RNG is bad.

**Comment by jkwatson** [comment]
We're using ThreadLocalRandom for the id generation, by default. Is Android's implementation of TLR bad? You might need to replace the IdGenerator implementation for Android, perhaps?

**Comment by jkwatson** [comment]
@jam0cam can you solve your issue here by implementing a custom IdGenerator?

**Comment by jam0cam** [comment]
I was, thanks for the suggestion

**Comment by jkwatson** [comment]
> I was, thanks for the suggestion

good to hear! closing this issue.

**Comment by sumitm-iiit** [comment]
@jam0cam : What custom IdGenerator did you use ? Is it possible for you to share that ?

**Comment by jkwatson** [comment]
> @jam0cam : What custom IdGenerator did you use ? Is it possible for you to share that ?

More recent versions of the SDK will detect if you're on Android and fall back to one that works. You shouldn't need to use a custom id generator any more.

**Comment by sumitm-iiit** [comment]
@jkwatson : Do you know from which version of SDK this issue is fixed ?

**Comment by jkwatson** [comment]
> @jkwatson : Do you know from which version of SDK this issue is fixed ?

https://github.com/open-telemetry/opentelemetry-java/releases/tag/v1.2.0

**Comment by yadavraju** [comment]
I am still seeing same dublocate trace id in android in v 1.11.0

<img width="1279" alt="Screen Shot 2022-02-17 at 7 33 20 PM" src="https://user-images.githubusercontent.com/9611971/154600747-25166ab7-956c-4490-9718-edf9191e25e4.png">

**Comment by jkwatson** [comment]
Can you show how your configuring your SDK?

**Comment by yadavraju** [comment]
`/*
 * Copyright The OpenTelemetry Authors
 * SPDX-License-Identifier: Apache-2.0
 */
package com.raju.disney.opentelemetry

import android.os.StrictMode
import android.os.StrictMode.ThreadPolicy
import io.opentelemetry.api.OpenTelemetry
import io.opentelemetry.api.common.Attributes
import io.opentelemetry.api.trace.Span
import io.opentelemetry.api.trace.SpanKind
import io.opentelemetry.api.trace.Tracer
import io.opentelemetry.api.trace.propagation.W3CTraceContextPropagator
import io.opentelemetry.context.Context
import io.opentelemetry.context.propagation.ContextPropagators
import io.opentelemetry.context.propagation.TextMapPropagator
import io.opentelemetry.context.propagation.TextMapSetter
import io.opentelemetry.exporter.jaeger.JaegerGrpcSpanExporter
import io.opentelemetry.exporter.logging.LoggingSpanExporter
import io.opentelemetry.exporter.otlp.trace.OtlpGrpcSpanExporter
import io.opentelemetry.sdk.OpenTelemetrySdk
import io.opentelemetry.sdk.resources.Resource
import io.opentelemetry.sdk.trace.SdkTracerProvider
import io.opentelemetry.sdk.trace.export.SimpleSpanProcessor
import io.opentelemetry.semconv.resource.attributes.ResourceAttributes
import java.util.concurrent.TimeUnit


/**
 * All SDK management takes place here, away from the instrumentation code, which should only access
 * the OpenTelemetry APIs.
 */
object OtelConfiguration {

    private fun init(): OpenTelemetry {
        // Export traces to Jaeger 
        val jaegerExporter = JaegerGrpcSpanExporter.builder()
            .setEndpoint("http://192.168.0.102:14250")
            .setTimeout(30, TimeUnit.SECONDS)
            .build()

        val oltpExporter =
            OtlpGrpcSpanExporter.builder().setEndpoint("http://192.168.0.102:4317")
                .setTimeout(2, TimeUnit.SECONDS).build()
        val serviceNameResource =
            Resource.create(Attributes.of(ResourceAttributes.SERVICE_NAME, "DisneyAndroid"))

        // Set to process the spans by the Jaeger Exporter
        val tracerProvider = SdkTracerProvider.builder()
            .addSpanProcessor(SimpleSpanProcessor.create(jaegerExporter))
            .addSpanProcessor(SimpleSpanProcessor.create(oltpExporter))
            .addSpanProcessor(SimpleSpanProcessor.create(LoggingSpanExporter.create()))
            .setResource(Resource.getDefault().merge(serviceNameResource))
            .build()

        val openTelemetry = OpenTelemetrySdk
            .builder()
            .setTracerProvider(tracerProvider)
            .setPropagators(ContextPropagators.create(W3CTraceContextPropagator.getInstance()))
            .build()

        // it's always a good idea to shut down the SDK cleanly at JVM exit.
        Runtime.getRuntime().addShutdownHook(Thread { tracerProvider.close() })
        return openTelemetry
    }

    fun getOpenTelemetry(): OpenTelemetry {
        return init()
    }

    fun getTracer(tracerName: String = "Android"): Tracer {
        return init().getTracer(tracerName)
    }

    fun createSpan1(tracer: Tracer, parentSpanName: String): Span =
        tracer.spanBuilder(parentSpanName).setSpanKind(SpanKind.CLIENT).startSpan()

    fun Tracer.createSpan(parentSpanName: String): Span =
        this.spanBuilder(parentSpanName).setSpanKind(SpanKind.CLIENT).startSpan()


    fun Tracer.createChildSpan(childSpanName: String, parentSpan: Span?): Span =
        this.spanBuilder(childSpanName)
            .setParent(Context.current().with(parentSpan))
            .setSpanKind(SpanKind.CLIENT).startSpan()

    private fun getTextMapPropagator(): TextMapPropagator = init().propagators.textMapPropagator

    fun injectSpanContext(): MutableMap<String, String> {
        val map: MutableMap<String, String> = hashMapOf()
        val setter = TextMapSetter<MutableMap<String, String>> { map1, key, value ->
            map1?.set(key, value)
        }
        getTextMapPropagator().inject(Context.current(), map, setter)
        return map
    }

}`

**Comment by yadavraju** [comment]
<img width="1119" alt="Screen Shot 2022-02-17 at 8 10 25 PM" src="https://user-images.githubusercontent.com/9611971/154604346-82c679be-42c2-41cb-9533-bdb44c983fcd.png">

I have created singletron class

**Comment by jkwatson** [comment]
Nothing looks amiss there to me. At Splunk, we're using OTel in our Android instrumentation and it's working 100% fine. I wonder if there's something odd you're doing with the Context that is keeping a span around as a parent in the Context that you aren't expecting.

Could you put together a simple sample application that reproduces the issue you're seeing? 

Here's the Splunk repository, which includes a sample app that does work (and you can point it at zipkin, or just look at the output of debug logs to prove it): https://github.com/signalfx/splunk-otel-android

**Comment by yadavraju** [comment]
Here is a sample app repo: https://github.com/yadavraju/DisneyCodeChallenge

could you please have a look? I am totally new to opentelimetry

**Comment by jkwatson** [comment]
> Here is a sample app repo: https://github.com/yadavraju/DisneyCodeChallenge
> 
> could you please have a look? I am totally new to opentelimetry

It looks like you're holding onto spans for the lifetime of each activity and re-using as the parent of other spans over and over. Each of those spans will have the same trace id, because the parent span is constant and has that trace id. 

You can't re-use parents like that, unless you want them to all be part of the same trace.

**Comment by yadavraju** [comment]
I tried to use Splunk library code. How can I add child span in my view model class when adding all the space added to single traces. similar to this image 

It happens when I open the same activity multiple times from the previous activity by going back and coming again. 

I want to create different traces every time open 

<img width="1789" alt="Screen Shot 2022-02-18 at 8 38 27 PM" src="https://user-images.githubusercontent.com/9611971/154785566-7481e063-f586-4b1c-8a3d-eddde38a6921.png">

    fun fetchFlightData() {
        viewModelScope.launch {
            val span = otel.startWorkflow("fetchFlightData:http:request")
            try {
                span.makeCurrent().use {
                    span.addEvent("Loading api data")
                    loadingObservableField.set(true)
                    repository.getFlightData(OtelConfiguration.injectSpanContext())
                        .catch { e ->
                            handleException(TAG, e, loadingObservableField)
                            val attributes = Attributes.of(
                                AttributeKey.stringKey(StatusCode.ERROR.name),
                                "/@GET/flight"
                            )
                            span.recordException(e, attributes)
                        }
                        .collect {
                            displayFlightData.value = it
                            loadingObservableField.set(false)
                            span.addEvent("Api data loaded: $it")
                        }
                }
            } finally {
                span.end()
            }
        }
    }

**Comment by jkwatson** [comment]
@jam0cam I recommend learning how the OpenTelemetry tracing system works, using something simple like a `main` method and a couple of threads. Writing instrumentation for Android is not trivial, due to needing to have a deep understanding of the threading model, and how that will interact with the OpenTelemetry Context propagation mechanisms.

This is definitely not the forum to try to debug something as complex as you're trying to do. You will probably need to dig deep and debug what's happening in your case, once you have a strong understanding of how OTel works.
